pipeline {
    agent any
    stages {
        
        stage('Staging'){
            steps{
                echo 'Starting staging job'
                build job: 'full-staging', parameters: [
                      string(name:'ENVIRONMENT', value: "staging")]
            }
        }
        stage('Merge'){
            steps{
                sh script: """
                    set -x
                    git branch -a
                    git checkout -b develop origin/develop
                    git checkout -b main origin/main
                    git merge develop
                """, label: "Merging code to main"
                sshagent(['GitHub_icapantonUnir_todo-list-aws']) {
                    sh "git push origin main"
                }

            }
        }
        stage('Production'){
            steps{
                
                echo 'Starting production job'
                build job: 'full-production', parameters: [
                      string(name:'ENVIRONMENT', value: "production")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}